[general]
name = "automake"
versions = ["1.16.3", "1.16.{1-3}", "1.16"]
dependencies = ["autoconf"]

[download]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE && curl -OL https://ftp.gnu.org/gnu/automake/automake-$VERSION.tar.gz"
step2 = "cd $DEVSET_ENVIRONMENT_SOURCE && tar -xvzf automake-$VERSION.tar.gz"

[unix]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE/automake-$VERSION && ./configure --prefix=$DEVSET_ENVIRONMENT_INSTALLATION/automake/"
step2 = "cd $DEVSET_ENVIRONMENT_SOURCE/automake-$VERSION && make -j$(nproc)"
step3 = "cd $DEVSET_ENVIRONMENT_SOURCE/automake-$VERSION && make install"
step4 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/automake/bin/* $DEVSET_ENVIRONMENT_BIN"
