[general]
name = "autoconf"
versions = ["2.70","2.{52-70}","2.50","2.{10-13}"]
dependencies = ["m4","make","perl"]

[user]
system_install = []
bootstrap = false

[download]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE && curl -OL https://ftp.gnu.org/gnu/autoconf/autoconf-$VERSION.tar.gz"
step2 = "cd $DEVSET_ENVIRONMENT_SOURCE && tar -xvzf autoconf-$VERSION.tar.gz"

[install]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE/autoconf-$VERSION && ./configure --prefix=$DEVSET_ENVIRONMENT_INSTALLATION/autoconf/"
step2 = "cd $DEVSET_ENVIRONMENT_SOURCE/autoconf-$VERSION && make -j$(nproc)"
step3 = "cd $DEVSET_ENVIRONMENT_SOURCE/autoconf-$VERSION && make install"
step4 = "rm -rf $DEVSET_ENVIRONMENT_SOURCE/autoconf-$VERSION"
step5 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/autoconf/bin/autoconf $DEVSET_ENVIRONMENT_BIN"
step6 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/autoconf/bin/autoheader $DEVSET_ENVIRONMENT_BIN"
step7 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/autoconf/bin/autom4te $DEVSET_ENVIRONMENT_BIN"
step8 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/autoconf/bin/autoreconf $DEVSET_ENVIRONMENT_BIN"
step9 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/autoconf/bin/autoscan $DEVSET_ENVIRONMENT_BIN"
step10 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/autoconf/bin/autoupdate $DEVSET_ENVIRONMENT_BIN"
step11 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/autoconf/bin/ifnames $DEVSET_ENVIRONMENT_BIN"

[uninstall]
step1 = "rm -rf $DEVSET_ENVIRONMENT_INSTALLATION/autoconf"
step2 = "rm -rf $DEVSET_ENVIRONMENT_BIN/autoconf"
step3 = "rm -rf $DEVSET_ENVIRONMENT_BIN/autoheader"
step4 = "rm -rf $DEVSET_ENVIRONMENT_BIN/autom4te"
step5 = "rm -rf $DEVSET_ENVIRONMENT_BIN/autoreconf"
step6 = "rm -rf $DEVSET_ENVIRONMENT_BIN/autoscan"
step7 = "rm -rf $DEVSET_ENVIRONMENT_BIN/autoupdate"
step8 = "rm -rf $DEVSET_ENVIRONMENT_BIN/ifnames"
