[general]
name = "binutils"
versions = ["2.35.1", "2.{7-35}", "2.33.1", "2.31.1", "2.{28-29}.1","2.{25-26}.1","2.23.1","2.{20-21}.1","2.19.1","2.16.1","2.13.{1-2}","2.{8-12}.1"]
dependencies = ["gcc", "make"]

[user]
system_install = []
bootstrap = false 

[download]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE && curl -OL https://ftp.gnu.org/gnu/binutils/binutils-$VERSION.tar.gz"
step2 = "cd $DEVSET_ENVIRONMENT_SOURCE && tar -xvzf binutils-$VERSION.tar.gz"

[install]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE/binutils-$VERSION && ./configure --prefix=$DEVSET_ENVIRONMENT_INSTALLATION/binutils/"
step2 = "cd $DEVSET_ENVIRONMENT_SOURCE/binutils-$VERSION && make -j$(nproc)"
step3 = "cd $DEVSET_ENVIRONMENT_SOURCE/binutils-$VERSION && make install"
step4 = "rm -rf $DEVSET_ENVIRONMENT_SOURCE/binutils-$VERSION"
step5 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/binutils/bin/addr2line $DEVSET_ENVIRONMENT_BIN"
step6 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/binutils/bin/ar $DEVSET_ENVIRONMENT_BIN"
step7 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/binutils/bin/as $DEVSET_ENVIRONMENT_BIN"
step8 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/binutils/bin/c++filt $DEVSET_ENVIRONMENT_BIN"
step9 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/binutils/bin/elfedit $DEVSET_ENVIRONMENT_BIN"
step10 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/binutils/bin/gprof $DEVSET_ENVIRONMENT_BIN"
step11 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/binutils/bin/ld $DEVSET_ENVIRONMENT_BIN"
step12 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/binutils/bin/ld.bfd $DEVSET_ENVIRONMENT_BIN"
step13 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/binutils/bin/nm $DEVSET_ENVIRONMENT_BIN"
step14 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/binutils/bin/objcopy $DEVSET_ENVIRONMENT_BIN"
step15 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/binutils/bin/objdump $DEVSET_ENVIRONMENT_BIN"
step16 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/binutils/bin/ranlib $DEVSET_ENVIRONMENT_BIN"
step17 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/binutils/bin/readelf $DEVSET_ENVIRONMENT_BIN"
step18 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/binutils/bin/size $DEVSET_ENVIRONMENT_BIN"
step19 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/binutils/bin/strings $DEVSET_ENVIRONMENT_BIN"
step20 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/binutils/bin/strip $DEVSET_ENVIRONMENT_BIN"
