[general]
name = "binutils"
versions = ["2.35.1", "2.{7-35}", "2.33.1", "2.31.1", "2.{28-29}.1","2.{25-26}.1","2.23.1","2.{20-21}.1","2.19.1","2.16.1","2.13.{1-2}","2.{8-12}.1"]
dependencies = ["gcc", "make"]

[user]
system_install = []
bootstrap = false 

[download]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE && curl -OL https://ftp.gnu.org/gnu/binutils/binutils-$VERSION.tar.gz"
step2 = "cd $DEVSET_ENVIRONMENT_SOURCE && tar -xvzf binutils-$VERSION.tar.gz"

[install]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE/binutils-$VERSION && ./configure --prefix=$DEVSET_ENVIRONMENT_INSTALLATION/binutils/"
step2 = "cd $DEVSET_ENVIRONMENT_SOURCE/binutils-$VERSION && make -j$(nproc)"
step3 = "cd $DEVSET_ENVIRONMENT_SOURCE/binutils-$VERSION && make install"
step4 = "rm -rf $DEVSET_ENVIRONMENT_SOURCE/binutils-$VERSION"
step5 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/binutils/bin/* $DEVSET_ENVIRONMENT_BIN"
