[general]
name = "cmake"
versions = ["3.19.2", "3.19.{0-2}"]
dependencies = ["make"]

[install]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE && curl -OL https://github.com/Kitware/CMake/releases/download/v$VERSION/cmake-$VERSION.tar.gz"
step2 = "cd $DEVSET_ENVIRONMENT_SOURCE && tar -xvzf cmake-$VERSION.tar.gz"

[install.unix]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE/cmake-$VERSION && ./bootstrap --prefix=$DEVSET_ENVIRONMENT_INSTALLATION/cmake/"
step2 = "cd $DEVSET_ENVIRONMENT_SOURCE/cmake-$VERSION && make -j$(nproc)"
step3 = "cd $DEVSET_ENVIRONMENT_SOURCE/cmake-$VERSION && make install"
step4 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/cmake/bin/* $DEVSET_ENVIRONMENT_BIN"
