[general]
name = "cmake"
versions = ["3.19.2","3.19.{0-2}","3.18.{0-5}","3.17.{0-5}","3.16.{0-9}","3.15.{0-7}","3.14.{0-7}","3.13.{0-5}","3.12.{0-4}","3.11.{0-4}","3.10.{0-3}","3.9.{0-6}","3.8.{0-2}","3.7.{0-2}","3.6.{0-3}","3.5.{0-2}","3.4.{0-3}","3.3.{0-2}","3.2.{0-3}","3.1.{0-3}","3.0.{0-2}"]
dependencies = ["gcc", "make"]

[user]
system_install = []
bootstrap = false

[download]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE && curl -OL https://github.com/Kitware/CMake/releases/download/v$VERSION/cmake-$VERSION.tar.gz"
step2 = "cd $DEVSET_ENVIRONMENT_SOURCE && tar -xvzf cmake-$VERSION.tar.gz"

[install]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE/cmake-$VERSION && ./bootstrap --prefix=$DEVSET_ENVIRONMENT_INSTALLATION/cmake/"
step2 = "cd $DEVSET_ENVIRONMENT_SOURCE/cmake-$VERSION && make -j$(nproc)"
step3 = "cd $DEVSET_ENVIRONMENT_SOURCE/cmake-$VERSION && make install"
step4 = "rm -rf $DEVSET_ENVIRONMENT_SOURCE/cmake-$VERSION*"
step5 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/cmake/bin/ccmake $DEVSET_ENVIRONMENT_BIN"
step6 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/cmake/bin/cmake $DEVSET_ENVIRONMENT_BIN"
step7 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/cmake/bin/cpack $DEVSET_ENVIRONMENT_BIN"
step8 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/cmake/bin/ctest $DEVSET_ENVIRONMENT_BIN"

[uninstall]
step1 = "rm -rf $DEVSET_ENVIRONMENT_INSTALLATION/cmake"
step2 = "rm -rf $DEVSET_ENVIRONMENT_BIN/ccmake"
step3 = "rm -rf $DEVSET_ENVIRONMENT_BIN/cmake"
step4 = "rm -rf $DEVSET_ENVIRONMENT_BIN/cpack"
step5 = "rm -rf $DEVSET_ENVIRONMENT_BIN/ctest"
