[general]
name = "gcc"
versions = ["10.2.0","10.{1-2}.0","9.{1-3}.0","8.{1-4}.0","7.{1-5}.0","6.{1-5}.0","5.{1-5}.0","4.9.{0-4}","4.8.{0-5}","4.7.{0-4}","4.6.{0-4}","4.5.{0-4}","4.4.{0-7}","4.3.{0-6}","4.2.{0-4}","4.1.{0-2}","4.0.{0-4}","3.4.{0-6}","3.3.{1-6}","3.3","3.2.{1-3}","3.2","3.1.1","3.1","3.0.{1-4}","3.0","2.95.{1-3}","2.95","2.8.{0-1}","1.42"]
dependencies = ["gcc-binutils","gcc-make"]

[user]
system_install = []
bootstrap = true 

[download]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE && curl -OL https://ftp.gnu.org/gnu/gcc/gcc-$VERSION/gcc-$VERSION.tar.gz"
step2 = "cd $DEVSET_ENVIRONMENT_SOURCE && tar -xvzf gcc-$VERSION.tar.gz"

[install]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE/gcc-$VERSION && ./contrib/download_prerequisites"
step2 = "mkdir $DEVSET_ENVIRONMENT_SOURCE/gcc-build"
step3 = "cd $DEVSET_ENVIRONMENT_SOURCE/gcc-build && ../gcc-$VERSION/configure --prefix=$DEVSET_ENVIRONMENT_INSTALLATION/gcc/ --disable-multilib --enable-languages=all"
step4 = "cd $DEVSET_ENVIRONMENT_SOURCE/gcc-build && make -j$(nproc)"
step5 = "cd $DEVSET_ENVIRONMENT_SOURCE/gcc-build && make install"
step6 = "rm -rf $DEVSET_ENVIRONMENT_SOURCE/gcc-build && rm -rf $DEVSET_ENVIRONMENT_SOURCE/gcc-$VERSION*"
step7 = "echo 'export LD_LIBRARY_PATH=${DEVSET_ENVIRONMENT_INSTALLATION/gcc/lib64:+${DEVSET_ENVIRONMENT_INSTALLATION/gcc/lib64}:}$LD_LIBRARY_PATH' >> $HOME/.devset/.env"
step8 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/c++ $DEVSET_ENVIRONMENT_BIN"
step9 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/cpp $DEVSET_ENVIRONMENT_BIN"
step10 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/g++ $DEVSET_ENVIRONMENT_BIN"
step11 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/gcc $DEVSET_ENVIRONMENT_BIN"
step12 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/gcc-ar $DEVSET_ENVIRONMENT_BIN"
step13 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/gccbrig $DEVSET_ENVIRONMENT_BIN"
step14 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/gccgo $DEVSET_ENVIRONMENT_BIN"
step15 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/gcc-nm $DEVSET_ENVIRONMENT_BIN"
step16 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/gcc-ranlib $DEVSET_ENVIRONMENT_BIN"
step17 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/gcov $DEVSET_ENVIRONMENT_BIN"
step18 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/gcov-dump $DEVSET_ENVIRONMENT_BIN"
step19 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/gcov-tool $DEVSET_ENVIRONMENT_BIN"
step20 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/gdc $DEVSET_ENVIRONMENT_BIN"
step21 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/gfortran $DEVSET_ENVIRONMENT_BIN"
step22 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/go $DEVSET_ENVIRONMENT_BIN"
step23 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/gofmt $DEVSET_ENVIRONMENT_BIN"
step24 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/lto-dump $DEVSET_ENVIRONMENT_BIN"
step25 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/x86_64-pc-linux-gnu-c++ $DEVSET_ENVIRONMENT_BIN"
step26 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/x86_64-pc-linux-gnu-g++ $DEVSET_ENVIRONMENT_BIN"
step27 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/x86_64-pc-linux-gnu-gcc $DEVSET_ENVIRONMENT_BIN"
step28 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/x86_64-pc-linux-gnu-gcc-10.2.0 $DEVSET_ENVIRONMENT_BIN"
step29 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/x86_64-pc-linux-gnu-gcc-ar $DEVSET_ENVIRONMENT_BIN"
step30 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/x86_64-pc-linux-gnu-gccbrig $DEVSET_ENVIRONMENT_BIN"
step31 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/x86_64-pc-linux-gnu-gccgo $DEVSET_ENVIRONMENT_BIN"
step32 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/x86_64-pc-linux-gnu-gcc-nm $DEVSET_ENVIRONMENT_BIN"
step33 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/x86_64-pc-linux-gnu-gcc-ranlib $DEVSET_ENVIRONMENT_BIN"
step34 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/x86_64-pc-linux-gnu-gdc $DEVSET_ENVIRONMENT_BIN"
step35 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/x86_64-pc-linux-gnu-gfortran $DEVSET_ENVIRONMENT_BIN"
step36 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/gcc $DEVSET_ENVIRONMENT_BIN/cc"

[uninstall]
step1 = "rm -rf $DEVSET_ENVIRONMENT_INSTALLATION/gcc"
step2 = "rm -rf $DEVSET_ENVIRONMENT_BIN/c++"
step3 = "rm -rf $DEVSET_ENVIRONMENT_BIN/cpp"
step4 = "rm -rf $DEVSET_ENVIRONMENT_BIN/g++"
step5 = "rm -rf $DEVSET_ENVIRONMENT_BIN/gcc"
step6 = "rm -rf $DEVSET_ENVIRONMENT_BIN/gcc-ar"
step7 = "rm -rf $DEVSET_ENVIRONMENT_BIN/gccbrig"
step8 = "rm -rf $DEVSET_ENVIRONMENT_BIN/gccgo"
step9 = "rm -rf $DEVSET_ENVIRONMENT_BIN/gcc-nm"
step10 = "rm -rf $DEVSET_ENVIRONMENT_BIN/gcc-ranlib"
step11 = "rm -rf $DEVSET_ENVIRONMENT_BIN/gcov"
step12 = "rm -rf $DEVSET_ENVIRONMENT_BIN/gcov-dump"
step13 = "rm -rf $DEVSET_ENVIRONMENT_BIN/gcov-tool"
step14 = "rm -rf $DEVSET_ENVIRONMENT_BIN/gdc"
step15 = "rm -rf $DEVSET_ENVIRONMENT_BIN/gfortran"
step16 = "rm -rf $DEVSET_ENVIRONMENT_BIN/go"
step17 = "rm -rf $DEVSET_ENVIRONMENT_BIN/gofmt"
step18 = "rm -rf $DEVSET_ENVIRONMENT_BIN/lto-dump"
step19 = "rm -rf $DEVSET_ENVIRONMENT_BIN/x86_64-pc-linux-gnu-c++"
step20 = "rm -rf $DEVSET_ENVIRONMENT_BIN/x86_64-pc-linux-gnu-g++"
step21 = "rm -rf $DEVSET_ENVIRONMENT_BIN/x86_64-pc-linux-gnu-gcc"
step22 = "rm -rf $DEVSET_ENVIRONMENT_BIN/x86_64-pc-linux-gnu-gcc-10.2.0"
step23 = "rm -rf $DEVSET_ENVIRONMENT_BIN/x86_64-pc-linux-gnu-gcc-ar"
step24 = "rm -rf $DEVSET_ENVIRONMENT_BIN/x86_64-pc-linux-gnu-gccbrig"
step25 = "rm -rf $DEVSET_ENVIRONMENT_BIN/x86_64-pc-linux-gnu-gccgo"
step26 = "rm -rf $DEVSET_ENVIRONMENT_BIN/x86_64-pc-linux-gnu-gcc-nm"
step27 = "rm -rf $DEVSET_ENVIRONMENT_BIN/x86_64-pc-linux-gnu-gcc-ranlib"
step28 = "rm -rf $DEVSET_ENVIRONMENT_BIN/x86_64-pc-linux-gnu-gdc"
step29 = "rm -rf $DEVSET_ENVIRONMENT_BIN/x86_64-pc-linux-gnu-gfortran"
step30 = "rm -rf $DEVSET_ENVIRONMENT_BIN/cc"
step31 = "sed -i '/export LD_LIBRARY_PATH=${DEVSET_ENVIRONMENT_INSTALLATION\/gcc\/lib64:+${DEVSET_ENVIRONMENT_INSTALLATION\/gcc\/lib64}:}$LD_LIBRARY_PATH/d' $HOME\/.devset\/.env"
