[general]
name = "gcc"
versions = ["10.2.0","10.{1-2}.0","9.{1-3}.0","8.{1-4}.0","7.{1-5}.0","6.{1-5}.0","5.{1-5}.0","4.9.{0-4}","4.8.{0-5}","4.7.{0-4}","4.6.{0-4}","4.5.{0-4}","4.4.{0-7}","4.3.{0-6}","4.2.{0-4}","4.1.{0-2}","4.0.{0-4}","3.4.{0-6}","3.3.{1-6}","3.3","3.2.{1-3}","3.2","3.1.1","3.1","3.0.{1-4}","3.0","2.95.{1-3}","2.95","2.8.{0-1}","1.42"]
dependencies = ["make", "binutils"]

[user]
system_install = []
bootstrap = true 

[download]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE && curl -OL https://ftp.gnu.org/gnu/gcc/gcc-$VERSION/gcc-$VERSION.tar.gz"
step2 = "cd $DEVSET_ENVIRONMENT_SOURCE && tar -xvzf gcc-$VERSION.tar.gz"

[unix]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE/gcc-$VERSION && ./contrib/download_prerequisites"
step2 = "mkdir $DEVSET_ENVIRONMENT_SOURCE/gcc-build"
step3 = "cd $DEVSET_ENVIRONMENT_SOURCE/gcc-build && ../gcc-$VERSION/configure --prefix=$DEVSET_ENVIRONMENT_INSTALLATION/gcc/ --disable-multilib --enable-languages=all"
step4 = "cd $DEVSET_ENVIRONMENT_SOURCE/gcc-build && make -j$(nproc)"
step5 = "cd $DEVSET_ENVIRONMENT_SOURCE/gcc-build && make install"
step6 = "if [ -e $HOME/.bash_profile ]; then echo 'export LD_LIBRARY_PATH=$DEVSET_ENVIRONMENT_INSTALLATION/gcc/lib64:$LD_LIBRARY_PATH' >> $HOME/.bash_profile; fi"
step7 = "if [ -e $HOME/.profile ]; then echo 'export LD_LIBRARY_PATH=$DEVSET_ENVIRONMENT_INSTALLATION/gcc/lib64:$LD_LIBRARY_PATH' >> $HOME/.profile; fi"
step8 = "if [ -e $HOME/.zshrc ]; then echo 'export LD_LIBRARY_PATH=$DEVSET_ENVIRONMENT_INSTALLATION/gcc/lib64:$LD_LIBRARY_PATH' >> $HOME/.zhsrc; fi"
step9 = "rm -rf $DEVSET_ENVIRONMENT_SOURCE/gcc-build && rm -rf $DEVSET_ENVIRONMENT_SOURCE/gcc-$VERSION"
step10 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/* $DEVSET_ENVIRONMENT_BIN"
step11 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gcc/bin/gcc $DEVSET_ENVIRONMENT_BIN/cc"
