[general]
name = "gettext"
versions = ["0.21","0.{13-20}","0.20.{1-2}","0.19.{1-8}","0.18.{1-3}","0.16.1","0.14.{1-6}","0.13.1","0.12.1","0.11.5","0.11.2","0.10.40"]
dependencies = ["gcc","m4","make"]

[user]
system_install = []
bootstrap = false

[download]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE && curl -OL https://ftp.gnu.org/gnu/gettext/gettext-$VERSION.tar.gz"
step2 = "cd $DEVSET_ENVIRONMENT_SOURCE && tar -xvzf gettext-$VERSION.tar.gz"

[install]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE/gettext-$VERSION && ./configure --prefix=$DEVSET_ENVIRONMENT_INSTALLATION/gettext/"
step2 = "cd $DEVSET_ENVIRONMENT_SOURCE/gettext-$VERSION && make -j$(nproc)"
step3 = "cd $DEVSET_ENVIRONMENT_SOURCE/gettext-$VERSION && make install"
step4 = "rm -rf $DEVSET_ENVIRONMENT_SOURCE/gettext-$VERSION*"
step5 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gettext/bin/autopoint $DEVSET_ENVIRONMENT_BIN"
step6 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gettext/bin/envsubst $DEVSET_ENVIRONMENT_BIN"
step7 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gettext/bin/gettext $DEVSET_ENVIRONMENT_BIN"
step8 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gettext/bin/gettextize $DEVSET_ENVIRONMENT_BIN"
step9 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gettext/bin/gettext.sh $DEVSET_ENVIRONMENT_BIN"
step10 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gettext/bin/msgattrib $DEVSET_ENVIRONMENT_BIN"
step11 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gettext/bin/msgcat $DEVSET_ENVIRONMENT_BIN"
step12 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gettext/bin/msgcmp $DEVSET_ENVIRONMENT_BIN"
step13 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gettext/bin/msgcomm $DEVSET_ENVIRONMENT_BIN"
step14 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gettext/bin/msgconv $DEVSET_ENVIRONMENT_BIN"
step15 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gettext/bin/msgen $DEVSET_ENVIRONMENT_BIN"
step16 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gettext/bin/msgexec $DEVSET_ENVIRONMENT_BIN"
step17 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gettext/bin/msgfilter $DEVSET_ENVIRONMENT_BIN"
step18 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gettext/bin/msgfmt $DEVSET_ENVIRONMENT_BIN"
step19 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gettext/bin/msggrep $DEVSET_ENVIRONMENT_BIN"
step20 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gettext/bin/msginit $DEVSET_ENVIRONMENT_BIN"
step21 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gettext/bin/msgmerge $DEVSET_ENVIRONMENT_BIN"
step22 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gettext/bin/msgunfmt $DEVSET_ENVIRONMENT_BIN"
step23 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gettext/bin/msguniq $DEVSET_ENVIRONMENT_BIN"
step24 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gettext/bin/ngettext $DEVSET_ENVIRONMENT_BIN"
step25 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gettext/bin/recode-sr-latin $DEVSET_ENVIRONMENT_BIN"
step26 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/gettext/bin/xgettext $DEVSET_ENVIRONMENT_BIN"

[uninstall]
step1 = "rm -rf $DEVSET_ENVIRONMENT_INSTALLATION/gettext"
step2 = "rm -rf $DEVSET_ENVIRONMENT_BIN/autopoint"
step3 = "rm -rf $DEVSET_ENVIRONMENT_BIN/envsubst"
step4 = "rm -rf $DEVSET_ENVIRONMENT_BIN/gettext"
step5 = "rm -rf $DEVSET_ENVIRONMENT_BIN/gettextize"
step6 = "rm -rf $DEVSET_ENVIRONMENT_BIN/gettext.sh"
step7 = "rm -rf $DEVSET_ENVIRONMENT_BIN/msgattrib"
step8 = "rm -rf $DEVSET_ENVIRONMENT_BIN/msgcat"
step9 = "rm -rf $DEVSET_ENVIRONMENT_BIN/msgcmp"
step10 = "rm -rf $DEVSET_ENVIRONMENT_BIN/msgcomm"
step11 = "rm -rf $DEVSET_ENVIRONMENT_BIN/msgconv"
step12 = "rm -rf $DEVSET_ENVIRONMENT_BIN/msgen"
step13 = "rm -rf $DEVSET_ENVIRONMENT_BIN/msgexec"
step14 = "rm -rf $DEVSET_ENVIRONMENT_BIN/msgfilter"
step15 = "rm -rf $DEVSET_ENVIRONMENT_BIN/msgfmt"
step16 = "rm -rf $DEVSET_ENVIRONMENT_BIN/msggrep"
step17 = "rm -rf $DEVSET_ENVIRONMENT_BIN/msginit"
step18 = "rm -rf $DEVSET_ENVIRONMENT_BIN/msgmerge"
step19 = "rm -rf $DEVSET_ENVIRONMENT_BIN/msgunfmt"
step20 = "rm -rf $DEVSET_ENVIRONMENT_BIN/msguniq"
step21 = "rm -rf $DEVSET_ENVIRONMENT_BIN/ngettext"
step22 = "rm -rf $DEVSET_ENVIRONMENT_BIN/recode-sr-latin"
step23 = "rm -rf $DEVSET_ENVIRONMENT_BIN/xgettext"
