[general]
name = "neovim"
versions = ["0.4.4","0.4.{0-4}","0.3.{0-8}","0.2.{0-2}","0.1.{0-7}"]
dependencies = ["autoconf","automake","cmake","gcc","libtool","make","pkg-config"]

[user]
system_install = ["unzip","m4"]
bootstrap = false

[download]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE && curl -L -o neovim-$VERSION.tar.gz https://github.com/neovim/neovim/archive/v$VERSION.tar.gz"
step2 = "cd $DEVSET_ENVIRONMENT_SOURCE && tar -xvzf neovim-$VERSION.tar.gz"

[install]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE/neovim-$VERSION && make -j$(nproc) CMAKE_BUILD_TYPE=Release CMAKE_INSTALL_PREFIX=$DEVSET_ENVIRONMENT_INSTALLATION/neovim/"
step2 = "cd $DEVSET_ENVIRONMENT_SOURCE/neovim-$VERSION && make install"
step3 = "rm -rf $DEVSET_ENVIRONMENT_SOURCE/neovim-$VERSION"
step4 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/neovim/bin/* $DEVSET_ENVIRONMENT_BIN"
