[general]
name = "oh-my-zsh"
versions = ["latest"]
dependencies = ["zsh"]

[user]
system_install = []
bootstrap = false

[download]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE && curl -L -o oh-my-zsh.zip https://github.com/ohmyzsh/ohmyzsh/archive/master.zip"
step2 = "cd $DEVSET_ENVIRONMENT_SOURCE && unzip oh-my-zsh.zip"
step3 = "mv ohmyzsh-master/ oh-my-zsh/"

[install]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE/oh-my-zsh && ./tools/install.sh --unattended"
step2 = "rm -rf $DEVSET_ENVIRONMENT_SOURCE/oh-my-zsh"
step3 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/dummy-executable $DEVSET_ENVIRONMENT_BIN/oh-my-zsh"

[uninstall]
step1 = "rm -rf $HOME/.oh-my-zsh"
step2 = "rm -rf $DEVSET_ENVIRONMENT_BIN/oh-my-zsh"
step3 = "mv $HOME/.zshrc $HOME/.zshrc.bak"
step4 = "mv $HOME/.zshrc.pre-oh-my-zsh $HOME/.zshrc"
