[general]
name = "perl"
versions = ["5.32.0","5.33.{0-5}","5.32.0","5.31.{0-11}","5.30.{0-3}","5.29.{0-10}","5.28.{0-3}","5.27.{0-11}","5.26.{0-3}","5.25.{0-12}","5.24.{0-4}","5.23.{0-9}","5.22.{0-4}","5.21.{0-11}","5.20.{0-3}","5.19.{0-11}","5.18.{0-4}","5.17.{0-11}","5.16.{0-3}","5.15.{0-9}","5.14.{0-4}","5.13.{0-11}","5.12.{0-5}","5.11.{0-5}","5.10.{0-1}","5.9.{0-5}","5.8.{0-9}","5.7.{0-3}","5.6.{0-2}"]
dependencies = ["gcc","make"]

[user]
system_install = []
bootstrap = false

[download]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE && curl -OL https://www.cpan.org/src/5.0/perl-$VERSION.tar.gz"
step2 = "cd $DEVSET_ENVIRONMENT_SOURCE && tar -xvzf perl-$VERSION.tar.gz"

[install]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE/perl-$VERSION && ./Configure -des -Dprefix=$DEVSET_ENVIRONMENT_INSTALLATION/perl/ -Dcc=gcc"
step2 = "cd $DEVSET_ENVIRONMENT_SOURCE/perl-$VERSION && make -j$(nproc)"
step3 = "cd $DEVSET_ENVIRONMENT_SOURCE/perl-$VERSION && make install"
step4 = "rm -rf $DEVSET_ENVIRONMENT_SOURCE/perl-$VERSION"
step5 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/corelist $DEVSET_ENVIRONMENT_BIN"
step6 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/cpan $DEVSET_ENVIRONMENT_BIN"
step7 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/enc2xs $DEVSET_ENVIRONMENT_BIN"
step8 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/encguess $DEVSET_ENVIRONMENT_BIN"
step9 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/h2ph $DEVSET_ENVIRONMENT_BIN"
step10 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/h2xs $DEVSET_ENVIRONMENT_BIN"
step11 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/instmodsh $DEVSET_ENVIRONMENT_BIN"
step12 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/json_pp $DEVSET_ENVIRONMENT_BIN"
step13 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/libnetcfg $DEVSET_ENVIRONMENT_BIN"
step14 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/perl $DEVSET_ENVIRONMENT_BIN"
step15 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/perl5.32.0 $DEVSET_ENVIRONMENT_BIN"
step16 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/perlbug $DEVSET_ENVIRONMENT_BIN"
step17 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/perldoc $DEVSET_ENVIRONMENT_BIN"
step18 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/perlivp $DEVSET_ENVIRONMENT_BIN"
step19 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/perlthanks $DEVSET_ENVIRONMENT_BIN"
step20 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/piconv $DEVSET_ENVIRONMENT_BIN"
step21 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/pl2pm $DEVSET_ENVIRONMENT_BIN"
step22 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/pod2html $DEVSET_ENVIRONMENT_BIN"
step23 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/pod2man $DEVSET_ENVIRONMENT_BIN"
step24 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/pod2text $DEVSET_ENVIRONMENT_BIN"
step25 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/pod2usage $DEVSET_ENVIRONMENT_BIN"
step26 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/podchecker $DEVSET_ENVIRONMENT_BIN"
step27 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/prove $DEVSET_ENVIRONMENT_BIN"
step28 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/ptar $DEVSET_ENVIRONMENT_BIN"
step29 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/ptardiff $DEVSET_ENVIRONMENT_BIN"
step30 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/shasum $DEVSET_ENVIRONMENT_BIN"
step31 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/splain $DEVSET_ENVIRONMENT_BIN"
step32 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/streamzip $DEVSET_ENVIRONMENT_BIN"
step33 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/xsubpp $DEVSET_ENVIRONMENT_BIN"
step34 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/perl/bin/zipdetails $DEVSET_ENVIRONMENT_BIN"

[uninstall]
step1 = "rm -f $DEVSET_ENVIRONMENT_BIN/corelist"
step2 = "rm -f $DEVSET_ENVIRONMENT_BIN/cpan"
step3 = "rm -f $DEVSET_ENVIRONMENT_BIN/enc2xs"
step4 = "rm -f $DEVSET_ENVIRONMENT_BIN/encguess"
step5 = "rm -f $DEVSET_ENVIRONMENT_BIN/h2ph"
step6 = "rm -f $DEVSET_ENVIRONMENT_BIN/h2xs"
step7 = "rm -f $DEVSET_ENVIRONMENT_BIN/instmodsh"
step8 = "rm -f $DEVSET_ENVIRONMENT_BIN/json_pp"
step9 = "rm -f $DEVSET_ENVIRONMENT_BIN/libnetcfg"
step10 = "rm -f $DEVSET_ENVIRONMENT_BIN/perl"
step11 = "rm -f $DEVSET_ENVIRONMENT_BIN/perl5.32.0"
step12 = "rm -f $DEVSET_ENVIRONMENT_BIN/perlbug"
step13 = "rm -f $DEVSET_ENVIRONMENT_BIN/perldoc"
step14 = "rm -f $DEVSET_ENVIRONMENT_BIN/perlivp"
step15 = "rm -f $DEVSET_ENVIRONMENT_BIN/perlthanks"
step16 = "rm -f $DEVSET_ENVIRONMENT_BIN/piconv"
step17 = "rm -f $DEVSET_ENVIRONMENT_BIN/pl2pm"
step18 = "rm -f $DEVSET_ENVIRONMENT_BIN/pod2html"
step19 = "rm -f $DEVSET_ENVIRONMENT_BIN/pod2man"
step20 = "rm -f $DEVSET_ENVIRONMENT_BIN/pod2text"
step21 = "rm -f $DEVSET_ENVIRONMENT_BIN/pod2usage"
step22 = "rm -f $DEVSET_ENVIRONMENT_BIN/podchecker"
step23 = "rm -f $DEVSET_ENVIRONMENT_BIN/prove"
step24 = "rm -f $DEVSET_ENVIRONMENT_BIN/ptar"
step25 = "rm -f $DEVSET_ENVIRONMENT_BIN/ptardiff"
step26 = "rm -f $DEVSET_ENVIRONMENT_BIN/shasum"
step27 = "rm -f $DEVSET_ENVIRONMENT_BIN/splain"
step28 = "rm -f $DEVSET_ENVIRONMENT_BIN/streamzip"
step29 = "rm -f $DEVSET_ENVIRONMENT_BIN/xsubpp"
step30 = "rm -f $DEVSET_ENVIRONMENT_BIN/zipdetails"
step31 = "rm -rf $DEVSET_ENVIRONMENT_INSTALLATION/perl"
