[general]
name = "pkg-config"
versions = ["0.29.2","0.29.{1-2}","0.{19-29}","0.27.1","0.18.1"]
dependencies = ["gcc","make"]

[user]
system_install = []
bootstrap = false

[download]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE && curl -OL https://pkg-config.freedesktop.org/releases/pkg-config-$VERSION.tar.gz"
step2 = "cd $DEVSET_ENVIRONMENT_SOURCE && tar -xvzf pkg-config-$VERSION.tar.gz"

[install]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE/pkg-config-$VERSION && ./configure --prefix=$DEVSET_ENVIRONMENT_INSTALLATION/pkg-config/ --with-internal-glib"
step2 = "cd $DEVSET_ENVIRONMENT_SOURCE/pkg-config-$VERSION && make -j$(nproc)"
step3 = "cd $DEVSET_ENVIRONMENT_SOURCE/pkg-config-$VERSION && make install"
step4 = "if [ -e $HOME/.bash_profile ]; then echo 'export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:$PKG_CONFIG_PATH' >> $HOME/.bash_profile; fi"
step5 = "if [ -e $HOME/.profile ]; then echo 'export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:$PKG_CONFIG_PATH' >> $HOME/.profile; fi"
step6 = "if [ -e $HOME/.zshrc ]; then echo 'export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig:$PKG_CONFIG_PATH' >> $HOME/.zhsrc; fi"
step7 = "rm -rf $DEVSET_ENVIRONMENT_SOURCE/pkg-config-$VERSION"
step8 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/pkg-config/bin/pkg-config $DEVSET_ENVIRONMENT_BIN"
step9 = "ln -s $DEVSET_ENVIRONMENT_INSTALLATION/pkg-config/bin/x86_64-unknown-linux-gnu-pkg-config $DEVSET_ENVIRONMENT_BIN"
