[general]
name = "zlib"
versions = ["1.2.11","1.2.{0-11}","1.1.{0-4}","1.0.{1-9}"]
dependencies = ["gcc","make"]

[user]
system_install = []
bootstrap = false

[download]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE && curl -OL https://zlib.net/fossils/zlib-$VERSION.tar.gz"
step2 = "cd $DEVSET_ENVIRONMENT_SOURCE && tar -xvzf zlib-$VERSION.tar.gz"

[install]
step1 = "cd $DEVSET_ENVIRONMENT_SOURCE/zlib-$VERSION && ./configure --prefix=$DEVSET_ENVIRONMENT_INSTALLATION/zlib"
step2 = "cd $DEVSET_ENVIRONMENT_SOURCE/zlib-$VERSION && make -j$(nproc)"
step3 = "cd $DEVSET_ENVIRONMENT_SOURCE/zlib-$VERSION && make install"
step4 = "rm -rf $DEVSET_ENVIRONMENT_SOURCE/zlib-$VERSION"
